#!/usr/bin/env bash

config="/etc/at30-fan-control/at30-fan-control.conf"
. "$config"

function get_cpu_temp {
	# /opt/vc/bin/vcgencmd measure_temp | grep -Eo "[0-9]*\." | sed 's/\.//g'
	cpu_temp=$(/usr/bin/sensors | grep temp1 | tail -n1|cut -f1 -dC | cut -f2 -d+ | sed -e "s/ //g")
	tshort="${cpu_temp:0:2}" ; echo "${tshort}"
	return ${tshort}
}

function set_pin {
	pin=$1
	value=$2

	echo $value > /sys/class/gpio/gpio$pin/value
}

function update_domoticz {
	cpu_temp=$(get_cpu_temp)

	#Updates Domotics Virtual Sensore [CPU Temperature] => (idx:58) 
	CT="Content-Type:application/json"
        DOMOREQ="curl http://${domoticz_server_ip}:${domoticz_server_port}/json.htm?type=command&param=udevice&idx=${sensor_idx}&nvalue=1&svalue=${cpu_temp}"
	echo $DOMOREQ
	RESPONSE=`$DOMOREQ`
	echo $RESPONSE
}

# Initialize pin
echo $fan_pin	> /sys/class/gpio/export
echo "out" 	> /sys/class/gpio/gpio$fan_pin/direction

echo $led_pin	> /sys/class/gpio/export
echo "out" 	> /sys/class/gpio/gpio$led_pin/direction

while true; do

	if [ $(get_cpu_temp) -ge $temp_high ] && [ ! "$cooling" ]; then
		# Turn on fan
		set_pin $fan_pin 1
		# Turn on led
		set_pin $led_pin 1

		cooling="true"
	fi

	if [ $(get_cpu_temp) -lt $temp_low ] && [ "$cooling" ]; then
		# Turn off fan
		set_pin $fan_pin 0
		# Turn off led
		set_pin $led_pin 0

		unset cooling
	fi

	# Update Domoticz
	update_domoticz

	sleep $check_delay

done

