#!/usr/bin/env bash

config="/etc/aimx6-fan-control/aimx6-fan-control.conf"
. "$config"

function get_cpu_temp {
	# /opt/vc/bin/vcgencmd measure_temp | grep -Eo "[0-9]*\." | sed 's/\.//g'
	cpu_temp=$(/usr/bin/sensors | grep temp1 | tail -n1|cut -f1 -dC | cut -f2 -d+ | sed -e "s/ //g")
	tshort="${cpu_temp:0:2}" ; echo "${tshort}"
	return ${tshort}
}

function set_pin {
	pin=$1
	value=$2

	echo $value > /sys/class/gpio/gpio$pin/value
}

function set_led {
	pin=$1
	value=$2

        echo $value > /sys/class/leds/$pin/brightness 
}


# Initialize pin
echo $fan_pin	> /sys/class/gpio/export
echo "out" 	> /sys/class/gpio/gpio$fan_pin/direction

while true; do

	if [ $(get_cpu_temp) -ge $temp_high ] && [ ! "$cooling" ]; then
		# Turn on fan
		set_pin $fan_pin 1
		# Turn on led
		set_led $led_pin 1

		cooling="true"
	fi

	if [ $(get_cpu_temp) -lt $temp_low ] && [ "$cooling" ]; then
		# Turn off fan
		set_pin $fan_pin 0
		# Turn off led
		set_led $led_pin 0

		unset cooling
	fi

	sleep $check_delay

done

